### ISSUE TITLE
[BUG] Application Gateway pool not shows at ScaleSet

### ISSUE THREAD

**Issue by sharondahan** [Azure/azure-libraries-for-java#698] opened 2019-02-21 06:57 UTC
**Describe the bug**
When trying to retrieve scaleSet using:
scaleSet.applicationGatewayBackendAddressPoolsIds()
or using inner:
scaleSet.inner().virtualMachineProfile.networkProfile().networkInterfaceConfigurations().get(0).ipConfigurations()

I don't see the Gateway backend pool I connected to the scaleSet, but when I use the Rest API call it is returned 
 "applicationGatewayBackendAddressPools": [
                      {
                        "id": "/subscriptions/7bfab27e-32ef-471f-a852-baa7da464c32/resourceGroups/AvivAKS/providers/Microsoft.Network/applicationGateways/myAppGateway/backendAddressPools/myAppGatewaywesteuGwTestSharon"
                      }
                    ] 

***Exception or Stack Trace***
Not relevant 

**To Reproduce**
Create scaleSet with Application Gateway 
Use the SDK to retrieve the scaleSet
Try to find the Application Gateway configuration

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**
I expected to find the Id on:
scaleSet.applicationGatewayBackendAddressPoolsIds()

**Screenshots**
Not relevant 

**Setup (please complete the following information):**
 - OS: Mac OS
 - IDE : IntelliJ
 - Version of the Library used: 18.0

**Additional context**
Not relevant

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X ] Bug Description Added
- [X ] Repro Steps Added
- [X ] Setup information Added

**Comment by praries880** [comment] 2019-02-26 23:11
@sharondahan We are looking into the issue. We will update the issue once we get to the root cause of the issue.

**Comment by yaohaizh** [comment] 2019-06-12 05:09
@sharondahan I cannot repro this issue on version 1.22.0 bits. Could you try it on the latest azure SDK version? 
I used this doc to create VMSS, then use the Azure SDK to get the application gate pool ids: 
https://docs.microsoft.com/en-us/azure/application-gateway/tutorial-create-vmss-cli

Code snippet:
```java
        PagedList<VirtualMachineScaleSet> vmss = azure.virtualMachineScaleSets().listByResourceGroup("myResourceGroupAG");
        for (VirtualMachineScaleSet vm : vmss) {
            System.out.println(vm.applicationGatewayBackendAddressPoolsIds());
        }
```
Result: 
```json
[/subscriptions/1c638cf4-608f-4ee6-b680-c329e824c3a8/resourceGroups/myResourceGroupAG/providers/Microsoft.Network/applicationGateways/myAppGateway/backendAddressPools/appGatewayBackendPool]
``

**Comment by praries880** [comment] 2019-07-02 20:09
@sharondahan We are closing the issue for now, kindly re-open the issue if it you are still runnign into the issue with the latest SDK version.

**Closed by praries880** 2019-07-02 20:09 UTC
Labels: Compute - VMSS, Investigate, Mgmt, needs-more-info
