### ISSUE TITLE
please add new region in Region.java

### ISSUE THREAD

**Issue by taroyutao** [Azure/azure-libraries-for-java#531] opened 2018-08-09 02:49 UTC
China azure has added two regions: china north2 and china east2. please add them in [Region.java](https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/fluentcore/arm/Region.java) in next version.

Thanks in advance.

**Comment by taroyutao** [comment] 2018-08-14 06:30
Any update?

**Comment by taroyutao** [comment] 2018-09-10 05:56
any update？

**Comment by jianghaolu** [comment] 2018-09-10 20:06
@taroyutao I'll add to the next release.

**Comment by jianghaolu** [comment] 2018-09-12 21:12
Duplicate of https://github.com/Azure/azure-libraries-for-java/issues/481, closing via https://github.com/Azure/azure-libraries-for-java/pull/573.

**Closed by jianghaolu** 2018-09-12 21:12 UTC
