### ISSUE TITLE
[BUG] Indefinite operations poll for VM Custom Script Extension call 

### ISSUE THREAD

**Issue by ashbondu** [Azure/azure-libraries-for-java#1146] opened 2020-03-25 18:27 UTC
Seeing indefinite operations poll for a VM custom script extension installation causing Azure throttling errors.

Azure client version - 1.26

Below example was running the operations poll for >12hrs 
Seen many in the same state.

2020-03-23 21:59:54,970 TRACE [RxIoScheduler-178]  returnCode=200 duration=(1078ms). PATCH https://management.azure.com/subscriptions/<subscriptionId>/resourceGroups/<ResourceGroup>/providers/Microsoft.Compute/virtualMachines/WSOL-Test0066?api-version=2019-03-01 Request=[size=1016 …]
2020-03-23 21:59:54,971 TRACE [RxIoScheduler-178] AzureApiEvent[timeStamp=1585000793,isGet=false,elapsedSeconds=1,retries=0,totRetryTime=0,maxRetryIntervalSeconds=0,isGiveUp=false]
2020-03-23 21:59:55,054 TRACE [RxIoScheduler-178]  returnCode=200 duration=(83ms). GET https://management.azure.com/subscriptions/<subscriptionId>/providers/Microsoft.Compute/locations/eastus/operations/20540c5d-9891-4073-8d70-2a88251cf174?api-version=2019-03-01
.
.
. 
2020-03-24 12:17:14,260 TRACE [RxIoScheduler-178]  returnCode=200 duration=(87ms). GET https://management.azure.com/subscriptions/<subscriptionId>/providers/Microsoft.Compute/locations/eastus/operations/20540c5d-9891-4073-8d70-2a88251cf174?api-version=2019-03-01

**Comment by yungezz** [comment] 2020-03-26 02:10
HI @weidongxu-microsoft  could you pls help to have a look? thanks

**Comment by weidongxu-microsoft** [comment] 2020-03-26 05:00
Hello @ashbondu 

We would like some information from you.

1. I assume you are using this "CustomScriptForLinux" extension. Correct me if I am wrong.
```
                .defineNewExtension("CustomScriptForLinux")
                    .withPublisher("Microsoft.OSTCExtensions")
                    .withType("CustomScriptForLinux")
                    .withVersion("1.4")
                    .withMinorVersionAutoUpgrade()
                    .withPublicSetting("fileUris",fileUris)
                    .withPublicSetting("commandToExecute", installCommand)
                .attach()
```

2. What is the response of the polling? Is it still "InProgress" like this?
```
{
  "startTime": "2020-03-26T04:13:30.3544491+00:00",
  "status": "InProgress",
  "name": ...
}
```

3. There might be multiple reasons why the VM custom script extension installation continue infinitely, e.g. script file not downloaded, script execution hanging on VM, etc. If possible would you let us know the nature of the script and command?

4. Regardless of the cause of the indefinite polling, I will try to find you a solution to cancel it or timeout it.

**Comment by weidongxu-microsoft** [comment] 2020-03-26 07:53
Here is one approach, to kill it via Interceptor (note that as this code, it affect all operation in "Microsoft.Compute" resource provider, also I assume it is still in "InProgress" state).

```
    private static class AzureAsyncOperation {
        private String status;
        private DateTime startTime;

        public String getStatus() {
            return status;
        }

        public void setStatus(String status) {
            this.status = status;
        }

        public DateTime getStartTime() {
            return startTime;
        }

        public void setStartTime(DateTime startTime) {
            this.startTime = startTime;
        }
    }

    private static class VmTimeoutInterceptor implements Interceptor {

        private static final JacksonAdapter jacksonAdapter = new AzureJacksonAdapter();
        private static final Duration timeoutDuration = Duration.standardMinutes(10); // timeout

        @Override
        public Response intercept(Chain chain) throws IOException {
            final String method = chain.request().method();
            final String path = chain.request().url().url().getPath();
            Response response = chain.proceed(chain.request());
            if (response.isSuccessful() && response.body() != null
                    && method.equalsIgnoreCase("GET")
                    && "Microsoft.Compute".equalsIgnoreCase(ResourceUtils.extractFromResourceId(path, "providers"))
                    && path.contains("/operations/")) {
                try {
                    final String body = response.peekBody(Long.MAX_VALUE).string();
                    final AzureAsyncOperation asyncOperation = jacksonAdapter.deserialize(body, AzureAsyncOperation.class);

                    if (asyncOperation != null
                            && asyncOperation.getStartTime() != null
                            && "InProgress".equalsIgnoreCase(asyncOperation.getStatus())) {
                        Duration duration = new Duration(asyncOperation.getStartTime(), DateTime.now());
                        if (duration.isLongerThan(timeoutDuration)) {
                            // error code to kill the polling
                            response = response.newBuilder()
                                    .code(408)
                                    .build();
                        }
                    }
                } catch (IOException e) {
                    // log and ignore
                }
            }
            return response;
        }
    }
```

Then add it to Azure client

```
            Azure azure = Azure.configure()
                    .withLogLevel(LogLevel.BODY_AND_HEADERS)
                    .withInterceptor(new VmTimeoutInterceptor())
                    ...
```

**Comment by weidongxu-microsoft** [comment] 2020-03-26 14:25
If one is using the async interface, it would be easier.

Cancel it.

```
    Observable<VirtualMachine> observable = ...
            .applyAsync();
    Subscription subscription = observable.subscribe();
    ...
    // if need to abort
    observable.unsubscribe();
```

or Timeout it.

```
    Observable<VirtualMachine> observable = ...
            .applyAsync()
            .timeout(10, TimeUnit.MINUTES);
    Subscription subscription = observable.subscribe();
```

**Comment by ashbondu** [comment] 2020-03-26 18:11
@ weidongxu-microsoft  Thanks for the suggestions.

Also these are VM custom script extension for Windows and not linux.
We are using the following way to create it.
```
if (vmExtensions.containsKey("VM_EXTENSION_NAME")) {
    VirtualMachineExtension.Update vmExtension = vm.update()
            .updateExtension("VM_EXTENSION_NAME")
            .withMinorVersionAutoUpgrade();

    vmExtension.withProtectedSetting("commandToExecute", commandToExec)
               .withPublicSetting("timestamp", System.currentTimeMillis());
    vmExtension.parent().apply();
} else {
    VirtualMachineExtension.UpdateDefinitionStages.WithAttach<VirtualMachine.Update> newVM = vm.update()
            .defineNewExtension("VM_EXTENSION_NAME")
            .withPublisher("VM_EXTENSION_PUBLISHER")
            .withType("VM_EXTENSION_TYPE")
            .withVersion("VM_EXTENSION_VERSION")
            .withMinorVersionAutoUpgrade();
    newVM.withProtectedSetting("commandToExecute", commandToExec)
            .withPublicSetting("timestamp", System.currentTimeMillis());
    newVM.attach().apply();
}
```

We had issues with this in earlier Azure client versions.
Will try it again and see if this good for us.
```
    Observable<VirtualMachine> observable = ...
            .applyAsync()
            .timeout(10, TimeUnit.MINUTES);
    Subscription subscription = observable.subscribe();
```

If that does not work, will fallback to the interceptor way.

Can we also provide a global timeout (to poll the operations) for the synchronous calls in the Azure client as an enhancement so we never run into indefinite poll calls?

**Comment by weidongxu-microsoft** [comment] 2020-03-27 02:05
@ashbondu

Good suggestion for the global timeout. I will take a look.

Generally the polling is controlled by service. I will try check with compute whether they have a policy there as well.

**Comment by weidongxu-microsoft** [comment] 2020-03-27 02:29
@mjconnection @Drewm3

A quick question on VM extension. Do we have timeout on service when install/update extension (the particular one is for custom script)?

**Comment by weidongxu-microsoft** [comment] 2020-03-27 03:45
PS: There appears to be a 90 min limit on script run. https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-windows#tips-and-tricks

Not sure whether this is other cause for the case of indefinite polling.

**Comment by Drewm3** [comment] 2020-03-30 15:58
@axayjo, could you help investigate this issue?

**Comment by weidongxu-microsoft** [comment] 2020-04-07 03:19
On client side, deleting the extension on certain condition.

```
    Map<String, VirtualMachineExtension> extensions = vm.listExtensions();
    VirtualMachineExtension extension = extensions.get(EXTENSION_NAME);
	if (extension != null && !"Succeeded".equalsIgnoreCase(extension.provisioningState())) {
        VirtualMachineExtensionInstanceView extensionInstanceView = extension.getInstanceView();
        if (extensionInstanceView.statuses() != null && !extensionInstanceView.statuses().isEmpty()) {
            if ("ProvisioningState/transitioning".equalsIgnoreCase(extensionInstanceView.statuses().iterator().next().code())) {
                azure.virtualMachines().manager().inner().virtualMachineExtensions().delete(RG_NAME, VM_NAME, EXTENSION_NAME);
            }
        }
    }
```

If `vm` is to be used afterward, remember to call `vm.refresh()`.

**Comment by amjads1** [comment] 2020-06-25 20:24
Based on my investigations and information gathered so far, this issue seems to be resolved. Closing this issue for now but feel free to re-open if issue still exists and I will take this forward. Thank you!

**Comment by Drewm3** [comment] 2020-06-25 21:12
Closing this one

**Closed by Drewm3** 2020-06-25 21:12 UTC
Labels: Compute - Extensions, Mgmt, Service Attention, customer-reported
