### ISSUE TITLE
No webapps folder is created when creating a new Linux web app with Tomcat

### ISSUE THREAD

**Issue by SummerSun** [Azure/azure-libraries-for-java#584] opened 2018-09-17 04:51 UTC
When creating a Windows web app with web container Tomcat, folder `webapps` will be created when the web app is created, but for Linux web app, there is no `webapps` folder created until users browse the web app.
From the experience with Windows web apps, we assume that there is always a `webapps` folder, and we continue the same operations for Linux web apps. And it causes the operation's failure.

Does this inconsistent behavior by design?

**Comment by jvano** [comment] 2018-09-19 06:35
Hi

The /webapps folder is specific to java workloads

In Java on App Service for Windows, you just ship code and the paths in the remote storage are provisioned at web app creation time.

For Linux, we rely on Container’s entrypoint script to hydrate the required paths in the remote storage and the container is initialized based on the first request.

In conclusion, it is by design.

Thanks,

Joaquín

**Comment by yaohaizh** [comment] 2019-09-02 07:37
Close this issue as it is by design.

**Closed by yaohaizh** 2019-09-02 07:37 UTC
Labels: App Services
