### ISSUE TITLE
Listing Vault Keys and Secrets requires additional access permissions

### ISSUE THREAD

**Issue by vrpanw** [Azure/azure-libraries-for-java#530] opened 2018-08-08 18:53 UTC
We are using the following API to access metadata for each key and secret defined in a Vault:
```
Azure.Authenticated azClient = Azure.authenticate(...);
Vault vlt = azClient.withDefaultSubscription().vaults().getById("some-resource-id");
vlt.keys().list();
vlt.secrets().list();
```
The call at line 3 and 4 result in `403 - Access denied`. The service principal already has global read access within the subscription. However, without the owner explicitly adding the permissions to `list` and `get` for the application user to the access policy at each vault level, this api is unusable.

We'd like the list and get calls moved away from the data plane (and into the management plane) so that we can use resource management roles on the api calls.

**Comment by yungezz** [comment] 2020-04-19 03:59
hi @vrpanw as you aware of, the list/get operation is data plane operation.  It's keyvault feature to set access policy on key/secret/cert layer other than vault mgmt layer. will close the issue as by design/won't fix now. Let us know if any other question/problem, thanks.

**Closed by yungezz** 2020-04-19 03:59 UTC
Labels: KeyVault, Mgmt, customer-reported
